#!/usr/bin/env php
<?php

use DatabaseJanitor\DatabaseJanitorCommand;
use Symfony\Component\Console\Application;
use Symfony\Component\Yaml\Yaml;

require __DIR__ . '/src/DatabaseJanitorCommand.php';
require __DIR__ . '/vendor/autoload.php';

$interface = new Application('database-janitor', 'rc1');
$configuration = Yaml::parseFile('.janitor.yml');
// Allow ability to "include" other configuration files.
if (isset($configuration['include'])) {
  $configuration2 = Yaml::parseFile($configuration['include']);
  $configuration = array_merge($configuration, $configuration2);
}
$command = new DatabaseJanitorCommand($configuration);
$interface->add($command);
$interface->setDefaultCommand($command->getName(), true);
$interface->run();
